global:
  resolve_timeout: 1m

route:
  receiver: 'discord-webhook'

receivers:
  - name: 'discord-webhook'
    webhook_configs:
      - url: 'https://discord.com/api/webhooks/1385859206627725372/FldO0-G5_Ea4hInW7FIRZbVhP38eF-dVSQ1wVyfXfFslaGRF0TCJvJ7EEbi7s44A4NEq'  # ganti dengan punyamu
        send_resolved: true
