services:  
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9091:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus.yml
    command:
      - '--config.file=/etc/prometheus.yml'
    extra_hosts:
      - "host.docker.internal:host-gateway"


  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3002:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin

  node-exporter:
    image: prom/node-exporter
    container_name: node-exporter
    ports:
      - "9101:9100"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
      - /var/lib/node_exporter/textfile_collector:/var/lib/node_exporter/textfile_collector
    command:
      - '--path.rootfs=/rootfs'
      - '--collector.textfile.directory=/var/lib/node_exporter/textfile_collector'
  
  webapp:
    image: ghcr.io/iqlalunesa/final-destination-12:latest
    container_name: final-web
    ports:
      - "8081:80"


volumes:
  grafana-storage:
